version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: app_db
    ports:
      - "3307:3306"
  web:
    image: app-test
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
